/*
 * Copyright 2002-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.keycloak;

public interface WebAuthnConstants {

    // Interface binded by FreeMarker template between UA and RP
    final String USER_ID = "userid";
    final String USER_NAME = "username";
    final String CHALLENGE = "challenge";
    final String RPID = "rpId";
    final String ORIGIN = "origin";
    final String ERROR = "error";
    final String PUBLIC_KEY_CREDENTIAL_ID= "publicKeyCredentialId";
    final String CREDENTIAL_ID = "credentialId";
    final String CLIENT_DATA_JSON = "clientDataJSON";
    final String AUTHENTICATOR_DATA = "authenticatorData";
    final String SIGNATURE = "signature";
    final String USER_HANDLE = "userHandle";
    final String ATTESTATION_OBJECT= "attestationObject";

    // key for storing onto UserModel's Attribute public key credential id generated by navigator.credentials.create()
    final String PUBKEY_CRED_ID_ATTR = "PUBLIC_KEY_CREDENTIAL_ID";

    // key for storing onto AuthenticationSessionModel's Attribute challenge generated by RP(keycloak)
    final String AUTH_CHALLENGE_NOTE = "WEBAUTH_CHALLENGE";
}
